### ISSUE TITLE
Add option for "smooth" lines

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#1]
Would be cool to have smoothed lines.

![Screen record from 2020-03-04 00 17 54](https://user-images.githubusercontent.com/6031763/75829148-bb38ab00-5dad-11ea-813e-cdfdc0b51382.gif)

BTW, really cool widget.

**Comment by stsdc** [comment]
Just saw readme, You probably already implemented this. Feel free to close, if its true!

**Comment by lcallarec** [comment]
Hi Stanisław,

Thanks you very much for your report. Smooth line are poorly implemented as [`LiveChart.Curve`](https://github.com/GNOME/gnome-system-monitor) serie renderer. I won't close this issue until result is close to your screenshot (I guess it cames from [gnome-system-monitor](https://github.com/GNOME/gnome-system-monitor)).

**Comment by stsdc** [comment]
@lcallarec  Yes, gnome-system-monitor uses [libdazzle](https://gitlab.gnome.org/GNOME/libdazzle)

**Comment by lcallarec** [comment]
@stsdc I re-implemented the smooth line close to libdazzle fast algorithm [here](https://github.com/lcallarec/live-chart/blob/master/src/smooth_line.vala#L24). Thanks to your report, I have been motivated to make this widget better. I close this issue, but if you have any question on how to use this widget, or if you have any request, please ask !

P.S.: It looks like [gnome-system-monitor](https://github.com/GNOME/gnome-system-monitor) doesn't use libdazzle, look at their [meson file](https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/blob/master/meson.build#L43) and their own [smooth graph implementation](https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/blob/master/src/load-graph.cpp#L306). But if you have any information, please share !

**Comment by stsdc** [comment]
@lcallarec You're right, old gnome-system-monitor doesn't use libdazzle, but new [Gnome Usage](https://wiki.gnome.org/Apps/Usage) does. My mistake :grimacing: sorry.
