### ISSUE TITLE
Create NEWS.md

### ISSUE THREAD

**Issue by gavr123456789** [lcallarec/live-chart#13]
First of all, thank you for continuing to develop this wonderful library. The graph widget is exactly what I was missing in Vala + GTK when I came from the Qt world.  
  
I suggest creating NEWS.md file that will contain the latest innovations, so that they are easier to navigate than by commits.

**Comment by lcallarec** [comment]
Hi @gavr123456789, thank you so much for your support, that means a lot to me.

Your suggestion is much appreciated, you're definitively right.

Here's the [NEWS.md](https://github.com/lcallarec/live-chart/blob/master/NEWS.md) !
