### ISSUE TITLE
Allow to change colour of serie by index

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#18]

**Comment by lcallarec** [comment]
Same comment as in https://github.com/lcallarec/live-chart/issues/17

**Comment by lcallarec** [comment]
Release [1.7.0](https://github.com/lcallarec/live-chart/releases/tag/1.7.0) is out and should fit your needs. 

* `Series` can be retrieved using [Chart.series](https://lcallarec.github.io/live-chart/Livechart/LiveChart.Series.html) property, by index using array access notation, or by name. Adding a new value to a serie is simpler : get the serie (either from where you created it or from chart's property) and add a value with [Serie.add(double value)](https://lcallarec.github.io/live-chart/Livechart/LiveChart.Serie.add.html). 
So, you'll be able to do something like `chart.series[2].set_main_color()`. Please note that you'll need to enclose that with a try/catch block.

* Hence [Chart.add_value](https://lcallarec.github.io/live-chart/Livechart/LiveChart.Chart.add_value.html) and [Chart.add_value_by_index](https://lcallarec.github.io/live-chart/Livechart/LiveChart.Chart.add_value_by_index.html) methods are now deprecated and will be removed in `LiveChart 2`.

**Comment by lcallarec** [comment]
@stsdc maybe you weren't noticed by my last comment. Fell free to close once it's ok on your side

**Comment by stsdc** [comment]
Works! Thanks a lot!
