### ISSUE TITLE
The curvature of the line changes when line goes out of the chart area

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#2]
live chart:
![Screen record from 2020-03-22 01 40 08](https://user-images.githubusercontent.com/6031763/77239738-5cad6280-6bde-11ea-861b-523e365871af.gif)

libdazzle:
![Screen record from 2020-03-22 01 47 12](https://user-images.githubusercontent.com/6031763/77239823-245a5400-6bdf-11ea-9b95-1b2c0dccfdec.gif)

**Comment by lcallarec** [comment]
Fixed in this [commit](https://github.com/lcallarec/live-chart/commit/83a7bf0d055687b1f47dccd4a091a1beb335b8fc)

![Peek 22-03-2020 14-10](https://user-images.githubusercontent.com/6905322/77250249-f4df3200-6c46-11ea-9437-3ada2a08fd0c.gif)

Thanks again for your report  @stsdc !
