### ISSUE TITLE
Porting to pure C

### ISSUE THREAD

**Issue by ayushbhat** [lcallarec/live-chart#26]
Not an issue, please close it as soon as you can. 
Just needed a suggestion.

I want to port this library to pure C, do I have to rewrite everything in C or I can take help of this Vala code to save my time?

**Comment by stsdc** [comment]
Why to port to C? Vala compiles to C and then to binary.

**Comment by ayushbhat** [comment]
Is there a way to extract the resulting C Interface of the functions, when it is compiled to C?

Actually I want to use this library in a C project.

**Comment by stsdc** [comment]
Check `valac.`

**Comment by ayushbhat** [comment]
Thanks!

**Comment by lcallarec** [comment]
You could just compile with `meson` and `ninja` : `meson build --buildtype=release && ninja -C build` and take a look in `build/src` folder : you'll find all transpiled C sources, the header file (`livechart.h`), and both static (`liblivechart_static.a`) & dynamic libraries (`liblivechart.so)` to link against your own C project.

For starting, I suggest you to take a look at the code generated in `build/examples`.

I opened a [dedicated discussion topic](https://github.com/lcallarec/live-chart/discussions?discussions_q=category%3A%22Use+LiveChart+C+flavour%22) if you need further help, it could interest other people. 

Let me know if you need any help or guidance, I'll be pleased to help !

**Comment by FlYnN91** [comment]
@lcallarec I've used your suggestion, compiled and built the release target. My confusion is about how to link the `.vapi` file and the `.vala` files that will contain the UI in my existing `makefile`. I already have a GTK3 UI and would like to add a chart into the existing application window.

**Comment by lcallarec** [comment]
Hi @FlYnN91, sorry for the delay. Do you have any repository to provide as example to help me to fully understand your context ?
