### ISSUE TITLE
Appearance: fill the area under the line with some color

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#3]
Would be cool to have this option.
![obraz](https://user-images.githubusercontent.com/6031763/77239881-d003a400-6bdf-11ea-8539-e30f8f371178.png)

**Comment by lcallarec** [comment]
Implemented `SmoothLineArea` and `LineArea` [here](https://github.com/lcallarec/live-chart/commit/5afddb9f28ec684dd6596a069294a40eb0b91eab). For now, the area color is the same as the line color, we can "only" control the alpha channel of the area.

![serie_smooth_line_area](https://user-images.githubusercontent.com/6905322/77264077-ed954400-6c99-11ea-9548-af1f1b1b8a3e.png)

**Comment by stsdc** [comment]
Amazing! Thank You.
Now I'm considering to try it in my Monitor app 😎
