### ISSUE TITLE
Consider using meson build system

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#4]

**Comment by lcallarec** [comment]
Yes, I will. 

Old Makefile will stay for incoming code coverage purpose, because meson build has [no support for detailed coverage for Vala](https://github.com/mesonbuild/meson/issues/799)...

**Comment by lcallarec** [comment]
Fixed [here](https://github.com/lcallarec/live-chart/commit/274b4845a9078b8d64ed7cda03eeb8f0572df570)
