### ISSUE TITLE
Releasing Past 1.9.1

### ISSUE THREAD

**Issue by yigitsever** [lcallarec/live-chart#43]
(also cc: @ryonakano)

hello, 

I was packaging [reco](https://github.com/ryonakano/reco) for [Archlinux (AUR)](https://aur.archlinux.org/packages/reco) and reco 5.0.0 depends on live-chart so I've packaged it on [AUR as well](https://aur.archlinux.org/packages/live-chart)

However, as far as I can tell, the current live-chart has moved past 1.9.1 release, could you release an up-to-date version? Thank you!

**Comment by lcallarec** [comment]
Hi @yigitsever !

Thanks for your request, I will release a 1.10.0 version before the end of the week. Stay tuned :)

**Comment by lcallarec** [comment]
Done, version 1.10.0 released !

**Comment by taozuhong** [comment]
https://github.com/msys2/MINGW-packages/pull/19680

MINGW package: mingw-w64-livechart-gtk4 has been submitted
