### ISSUE TITLE
Usage explanation

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#5]
Will it be a shared library? Or should I just clone it to my project an and use it as subrepository?

**Comment by lcallarec** [comment]
Honestly, I don't think that kind of library should be system-wide shared. 

I think the best option will be to use use git submodules. If your project is built with meson, it's a piece of cake : just build live-chart before your own code and add `livechart_dep` as dependency for your own project.

**Comment by lcallarec** [comment]
My bad.

Integrate live-charts to a project built with meson is simpler than I though. You don't need to struggle with git submodules.

Instead, there's [Meson wrap feature](https://mesonbuild.com/Wrap-dependency-system-manual.html) which can fetch any source code from git during build ; then, you can simply use livechart as any [Meson subroject](https://mesonbuild.com/Subprojects.html). I tested, it works like a charm ;)

**Comment by stsdc** [comment]
Wow. Didn't knew about this! Will try, thanks!

**Comment by stsdc** [comment]
It works!
![obraz](https://user-images.githubusercontent.com/6031763/78308358-90767980-7548-11ea-9706-b5abf61313de.png)

**Comment by lcallarec** [comment]
Wonderful ! 
Please ask if you need something else.
