### ISSUE TITLE
Appearence: allow to hide labels, legend etc

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#8]
I want to display a chart in a small box and labels and legends are cluttering the chart.
Also would be nice to control chart border and background guidelines. 
![image](https://user-images.githubusercontent.com/6031763/78462884-e711be00-76d6-11ea-9381-b0613a9f4e36.png)

**Comment by lcallarec** [comment]
Looks like good improvements. I'll work on it soon.

However, I'm not sure what do you meant by "chart border". Is it to mimic the grey border and margin of the panel of opened files above button line in your screenshot ?

**Comment by stsdc** [comment]
The border I meant:
![obraz](https://user-images.githubusercontent.com/6031763/78573752-5e576700-7829-11ea-8a79-33bd919493ad.png)

**Comment by stsdc** [comment]
Also would be nice to control:
 - grid colour
 - grid lines (only vertical or horizontal)
 - grid line style (solid, dotted, dashed) 
 - grid line weight

Sorry that's a lot :grimacing: 😅️

**Comment by lcallarec** [comment]
Working on it. It'll be ready soon.

**Comment by lcallarec** [comment]
In release 1.3.0 : 

* Legend can de hidden
* Labels can de hidden
* Guidelines can be hidden
* Custom width, color and dash style on guidelines
* Axis can be hidden or customized (width, color and dash style)

Documentation has been updated to reflect the changes. Please let me know if it's clear enough or if the documentation needs to be rewritten.

**Comment by stsdc** [comment]
Wondering how to easily clear a serie :thinking: 

e.g.:
1. clicking new process to load new buffer which contains CPU usage history
2. previous buffer is cleared
3. adding new buffer (I'm saving data in ArrayList<double>) (should I do `foreach` here?)

What do You recommend?

**Comment by lcallarec** [comment]
Hmmm, just a question. You are storing CPU usage history in an ArrayList, but are you storing values and related timestamps ?

**Comment by stsdc** [comment]
I'm not storing them, because chart is in the representative layer and process cpu history is in  lower layer of model-controller. Every 2s I'm updating ArrayLists of all processes. And I thought maybe there is possibility to push ArrayList to chart to instantly draw a chart. And after this to draw it normally, adding points in periods of time. I don't know, maybe my way of thinking on this is wrong.

**Comment by lcallarec** [comment]
There's nothing wrong, as long as it fits your needs :)

So, right now, the solution will be to 
* clear the underlying `Values` object of a serie renderer
* manually compute back, for each point, the related timestamp (2s behind now for each measure in your case)

```vala
var renderer = new LiveChart.SmoothLineArea();
var cpu = new LiveChart.Serie("CPU", renderer);

var chart = new LiveChart.Chart();
chart.add_serie(cpu);
//Other stuff

//To add the CPU history 

var values = renderer.get_values();
values.clear(); // Clear all the data

//Here's your own data from ArrayList<double>
var cpu_history = new Gee.ArrayList<double?>();
cpu_history.add(10);
cpu_history.add(30);
cpu_history.add(20);
cpu_history.add(40);
cpu_history.add(20);
cpu_history.add(60);
cpu_history.add(30);
cpu_history.add(90);

var refresh_rate_is_ms = 2000; //your own refresh rate in milliseconds
var now = GLib.get_real_time() / 1000; //now in milliseconds

//the  timestamp of the first point
//we are considering that it is "now", but because of your data structure
//it can be between now and now - 2secs), we can't guess
var ts = now - (cpu_history.size * refresh_rate_is_ms); 

cpu_history.foreach((value) => {
    values.add({ts, value});    
    ts += refresh_rate_is_ms;
    return true;
});
```

By the way, I also need such feature, so I will add some convenient methods to help dealing with the underlying `Values` object.

But if you don't store a timestamp alongside your data, you'll need to guess them with extra code, and by "guess" I mean that your data points time precision will not be guaranteed (epsilon = 2000ms in your case).

Maybe I could add conversion methods between timestamp unaware collection and `TimestampedValue` in LiveChart library ; let me think if it makes sense.

**Comment by stsdc** [comment]
Works like a charm 😌️ 
Built in conversion to a `TimestampedValue` would be awesome :nerd_face: 
![Screen record from 2020-04-09 23 05 43](https://user-images.githubusercontent.com/6031763/78941130-5ca2d300-7ab7-11ea-95d0-1de273fb9c28.gif)
.

**Comment by lcallarec** [comment]
Opened https://github.com/lcallarec/live-chart/issues/12, I close this one, the main issue about hiding chart parts and grid configuration has been resolved.
